services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: .
    image: projeto-final/backend
    env_file:
      - .env
    environment:
      APP_NAME: InstaClone
      DB_HOST: mysql
      DB_PORT: 3306
      DB_CONNECTION: mysql
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      APP_ENV: local
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - app_storage:/app/storage
    depends_on:
      - mysql
volumes:
  mysql_data: {}
  app_storage: {}
